apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../base/istio-policies

replicas:
- name: details-deployment
  count: 2

replicas:
- name: productpage-deployment
  count: 2

replicas:
- name: ratings-deployment
  count: 1