apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    matchLabels:
      app: productpage
  replicas: 2
  template:
    metadata:
      labels:
        app: productpage
    spec:
      serviceAccountName: product-service-account
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: details
        image: iad.ocir.io/idmaqhrbiuyo/product-ms:v0.1
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 2   
        resources:
          limits:
            cpu: "256m" 
            memory: "512Mi"
          requests:
            cpu: "256m"
            memory: "512Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: oci.oraclecloud.com/oke-is-preemptible
                operator: In
                values:
                - "true"     
      tolerations:
      - key: oci.oraclecloud.com/oke-is-preemptible
        operator: Exists
        effect: "NoSchedule"
