apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpYWQub2Npci5pbyI6eyJ1c2VybmFtZSI6ImlkbWFxaHJiaXV5by9hcG9vcnZhLmFsc2hpQGltcGV0dXMuY29tIiwicGFzc3dvcmQiOiIzKE9RbXVbUDBnfTI6OkN0UCNaOSIsImVtYWlsIjoiYXBvb3J2YS5hbHNoaUBpbXBldHVzLmNvbSIsImF1dGgiOiJhV1J0WVhGb2NtSnBkWGx2TDJGd2IyOXlkbUV1WVd4emFHbEFhVzF3WlhSMWN5NWpiMjA2TXloUFVXMTFXMUF3WjMweU9qcERkRkFqV2prPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ocirsecret
  namespace: dev
type: kubernetes.io/dockerconfigjson