apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgAKSm/m5bHcai6qYLInY09UA6In06Ay5q/0Es24oFkWJL/tUkPB8uQq/NnJdwQB7zcq45a01zIlADHJT1zKkt4gTsy+xhsXIICv2JIasAZutqbvTFciBm/+Fccl8Ak9bl4c4QjnNp/3D+Jl/rrHLiBTwqM97fSxqg/ReChZnUpocsLhAiMW2dAd8A2K9uw9ywIppRZXbt1iTkoNld84Lht2QtVRYCOpNddpb6BO8Ta1INxJ0Db0ynTLpmlQxC16gRP/J19NdJFRL0sFlAZjUeOeSdOrLn6IX/eE+an93DBfFAKXNSiJn//BZPjcXYIAlA17oCt4IoHhxFa7RHapD4dpSive2mPl+0isJ8eeqdx0QySVmKJxA3SAfUBwRurHBc+pR9apuyOg2KZi/ERvX++CwCVjMziVpcrDB0ygJpk/GT/2mv4m9cQzIgLRo6T+0keV9C1HY1DJuY7vGM8jPDTlPJbVRfs3+Msb0NeONcGHj1I+WfnJJSZK5hmZE626k9/ag4lKqziX3k2oMmqZ0DyjKwikgSGCaV7VOI35ARe8ZBAmK8pcobPqjhzadKVZgWBoQx+HWEFG4eAIiWWq/RjQ2KYC2HG8RNE/YIWtwnOEtB+6yKpiulWQ62g1oeHfdnXlOM5lXEudTXkjzVodcIRj3Hv95Y+jP6qG256zq8Oq6ALyAY3VP91cEoVPQ3KByu4/H0couWpLNps9ZA==
  template:
    metadata:
      creationTimestamp: null
      name: database
      namespace: dev